name: Node.js CI for FE

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.14.x'

      - name: install serverless framework
        run: npm i -g serverless

      - name: install serverlees 'finch' plugin
        run: npm install --save serverless-finch

      - name: building Shopping Cart application
        run: |
          npm i 
          npm run build --if-present
        working-directory: ./usc-widget
      
      - name: building React application
        run: |
          npm i 
          npm run build --if-present
        working-directory: ./usc-outlet

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
        
      - name: deploy static site with serverless
        run: serverless client deploy --no-confirm
        working-directory: ./usc-outlet

        env:
          CI: true
