name: Node.js CI for FE

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.14.1'
    - run: npm install
    - run: npm run build --if-present
    - run: npm test
      env:
        CI: true
